let token = "";
let current = null;
const selected = new Set();
let busy = false;
let activeAction = null;
const $ = id => document.getElementById(id);
const esc = value => String(value ?? "").replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[ch]);
function notice(message, good=false){const box=$("notice");box.textContent=message;box.classList.remove("hidden");box.classList.toggle("good",good);setTimeout(()=>box.classList.add("hidden"),9000)}
async function request(path, data){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-G100-Token":token},body:JSON.stringify(data)});const body=await response.json();if(!response.ok)throw Error(body.error||"Request failed");return body}
function selectedSerials(){return [...selected].filter(serial=>current.state.probes.some(p=>p.serial===serial))}
function render(){if(!current)return;const state=current.state;
  const release=state.release;$("release-status").innerHTML=activeAction==="/api/release"?"Checking the latest GitHub release and verifying firmware files…":release?`Latest release: <strong>${esc(release.tag)}</strong> · Firmware ${esc(release.version)} · <a href="${esc(release.url)}" target="_blank" rel="noopener">GitHub release</a>`:esc(state.release_error||"No firmware release checked yet.");
  const probes=$("probes");probes.classList.toggle("empty",!state.probes.length);
  probes.innerHTML=state.probes.length?state.probes.map(p=>{const i=state.inspected[p.serial],checked=selected.has(p.serial)?"checked":"";const detail=i?(i.error?`<div class="detail">${esc(i.error)}</div>`:`<div class="detail">MCU UID: ${esc(i.uid)} · Internal Flash: ${esc(i.internal_flash)}</div><div class="contents">${i.images.map(s=>`<span>${["A","B","Factory"][s.slot]}: ${esc(s.state)}${s.payload_bytes?` · ${esc(s.payload_bytes)} B`:``}</span>`).join("")}</div><div class="detail">Boot metadata: ${esc(i.metadata.filter(Boolean).length)} valid sector(s)</div>`):`<div class="detail">Not inspected yet.</div>`;return `<label class="probe"><input type="checkbox" data-serial="${esc(p.serial)}" ${checked} ${state.running?"disabled":""}><div><div class="probe-title">ST-LINK ${esc(p.usb_product_id)} <span class="badge ${i&&i.error?"bad":""}">${i?(i.error?"INSPECTION FAILED":"INSPECTED"):"CONNECTED"}</span></div><div class="probe-sub">Probe serial: ${esc(p.serial)}</div>${detail}</div></label>`}).join(""):"No ST-LINK found. Check USB connection and driver.";
  probes.querySelectorAll("input[data-serial]").forEach(input=>input.addEventListener("change",()=>{input.checked?selected.add(input.dataset.serial):selected.delete(input.dataset.serial);renderButtons()}));
  const progress=$("progress"),boards=Object.values(state.boards);progress.classList.toggle("empty",!boards.length);progress.innerHTML=boards.length?boards.map(b=>`<div class="progress-item"><div class="progress-head"><span>${esc(b.uid)}</span><span>${esc(b.state.toUpperCase())}</span></div><div class="progress-meta">${esc(b.phase)} · ${esc(b.percent)}%${b.state==="running"?(b.estimate_overdue?` · taking longer than estimated`:` · approximately ${esc(Math.ceil(b.estimated_remaining_seconds/60))} min remaining`):``}${b.error?` · ${esc(b.error)}`:``}</div><div class="bar"><span style="width:${Math.max(0,Math.min(100,b.percent))}%"></span></div></div>`).join(""):"No run started.";
  const report=$("report");report.classList.toggle("hidden",!state.report_path);if(state.report_path){const passed=boards.filter(b=>b.state==="passed").length,partial=boards.filter(b=>b.state==="partial").length,failed=boards.filter(b=>b.state==="failed").length;report.innerHTML=`<strong>Run ${esc(state.run_id)} complete:</strong> ${passed} passed, ${partial} partial, ${failed} failed.<br><a href="/api/report" download>Download summary report</a><div class="detail">Full logs and verified backups: ${esc(state.report_path)}</div>${state.general_error?`<div class="detail">${esc(state.general_error)}</div>`:``}`}
  renderButtons();
}
function renderButtons(){const running=current?.state.running||busy,serials=selectedSerials(),valid=serials.length&&serials.every(s=>current.state.inspected[s]?.uid&&!current.state.inspected[s]?.error),mode=document.querySelector('input[name="mode"]:checked').value;$("scan").disabled=running;$("release").disabled=running;$("inspect").disabled=running||!serials.length;$("start").disabled=running||!valid||(mode==="install"&&!current.state.release)}
async function refresh(){try{const response=await fetch("/api/state",{cache:"no-store"});current=await response.json();token=current.token;render()}catch(error){notice(error.message)}}
async function action(path,data={}){if(busy)return;busy=true;activeAction=path;render();try{await request(path,data);await refresh()}catch(error){notice(error.message);await refresh()}finally{busy=false;activeAction=null;render()}}
$("scan").addEventListener("click",async()=>{selected.clear();await action("/api/scan")});
$("release").addEventListener("click",()=>action("/api/release"));
$("inspect").addEventListener("click",()=>action("/api/inspect",{serials:selectedSerials()}));
document.querySelectorAll('input[name="mode"]').forEach(r=>r.addEventListener("change",renderButtons));
$("start").addEventListener("click",async()=>{const serials=selectedSerials(),mode=document.querySelector('input[name="mode"]:checked').value,count=serials.length;if(!count)return;const uids=serials.map(s=>current.state.inspected[s].uid);const verb=mode==="install"?"erase and install the latest release":"erase only";if(!confirm(`You are about to ${verb} on ${count} board(s):\n\n${uids.join("\n")}\n\nVerified backups will be made first. Continue?`))return;const typed=prompt(`To confirm full deletion, type ERASE ${count}`);if(typed===null)return;await action("/api/start",{mode,serials,confirmation:typed,max_parallel:Number($("workers").value),release_tag:current.state.release?.tag})});
refresh().then(async()=>{await action("/api/scan");await action("/api/release")});
setInterval(refresh,2000);
