let token = "", current = null, busy = false, activeAction = null, pendingReview = null;
const selected = new Set(), networkSelected = new Set();
const $ = id => document.getElementById(id);
const esc = value => String(value ?? "").replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[ch]);
const mode = () => document.querySelector('input[name="mode"]:checked').value;
const renderedMarkup = new Map();
function setMarkup(id,html){if(renderedMarkup.get(id)!==html){$(id).innerHTML=html;renderedMarkup.set(id,html);}}
const duration = seconds => `${Math.floor((seconds||0)/60)}m ${(seconds||0)%60}s`;
function notice(message, good=false){const box=$("notice");box.textContent=message;box.classList.remove("hidden");box.classList.toggle("good",good);}
async function request(path,data){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-G100-Token":token},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error||"Request failed");return b;}
function selectedIds(){if(!current)return [];return mode()==="network-update"?[...networkSelected].filter(uid=>current.state.network_boards.some(b=>b.uid===uid)):[...selected].filter(s=>current.state.probes.some(p=>p.serial===s));}
function render(){if(!current)return;const s=current.state;
 if(s.running){document.querySelectorAll('input[name="mode"]').forEach(el=>el.checked=el.value===s.mode);const active=s.mode==='network-update'?networkSelected:selected;active.clear();Object.keys(s.boards).forEach(id=>active.add(id));}
 const net=mode()==="network-update",erasing=mode()==="erase-only";
 $("swd-section").classList.toggle("hidden",net);$("network-section").classList.toggle("hidden",!net);
 $("route-help").textContent=net?"Only Ethernet and independent board power are required. A prepared, empty board can receive its first main application here.":mode()==="network-install"?"Connect ST-LINK, independent board power and Ethernet. The installer closes SWD before sending the main application.":erasing?"The board will be left empty after verified deletion.":"ST-LINK writes the complete installation. Connect Ethernet for the final runtime checks.";
 $("operation-warning").textContent=net?"The selected boards will restart. Their current confirmed image remains available until the new firmware passes runtime checks.":"This deletes the selected boards' internal Flash and external NOR, including settings and access records. Verified backups are saved first. UID, OTP and option bytes are preserved.";
 const r=s.release;$("release-status").innerHTML=activeAction==="/api/release"?"Downloading and verifying release files…":r?`<strong>${esc(r.tag)}</strong> · Firmware ${esc(r.version)} · ${esc(r.source)} ${r.network_supported?'<span class="badge">ETHERNET READY</span>':'<span class="badge bad">SWD RELEASE ONLY</span>'}${r.url?` · <a href="${esc(r.url)}" target="_blank" rel="noopener">Release details</a>`:''}`:esc(s.release_error||"No firmware loaded. Use the included package or fetch a release.");
 setMarkup("probes",s.probes.length?s.probes.map(p=>{const i=s.inspected[p.serial];return `<label class="probe"><input type="checkbox" data-serial="${esc(p.serial)}" ${selected.has(p.serial)?'checked':''} ${s.running?'disabled':''}><div><strong>ST-LINK ${esc(p.usb_product_id)}</strong><div class="detail">${esc(p.serial)}</div>${i?i.error?`<div class="error">${esc(i.error)}</div>`:`<div class="detail">UID ${esc(i.uid)} · ${esc(i.internal_flash)}</div><div class="contents">${i.images.map(v=>`<span>${['A','B','Recovery'][v.slot]}: ${esc(v.state)}</span>`).join('')}</div>`:'<div class="detail">Inspection required</div>'}</div></label>`;}).join(''):"No probes scanned yet.");
 $("probes").querySelectorAll('[data-serial]').forEach(el=>el.onchange=()=>{el.checked?selected.add(el.dataset.serial):selected.delete(el.dataset.serial);renderButtons();});
 setMarkup("network-boards",s.network_boards.length?s.network_boards.map(b=>`<label class="probe"><input type="checkbox" data-uid="${esc(b.uid)}" ${networkSelected.has(b.uid)?'checked':''} ${s.running||!b.has_key||b.error?'disabled':''}><div><strong>${esc(b.label||b.uid)}</strong><div class="detail">${esc(b.ip||'Address discovered at connection')} · ${b.online?'Discovered':'Saved board'} · ${esc(b.version||b.last_version||'')}</div>${b.error?`<div class="error">${esc(b.error)}</div>`:''}</div></label>`).join(''):"No prepared boards discovered. Check power, Ethernet and routing.");
 $("network-boards").querySelectorAll('[data-uid]').forEach(el=>el.onchange=()=>{el.checked?networkSelected.add(el.dataset.uid):networkSelected.delete(el.dataset.uid);renderButtons();});
 const boards=Object.values(s.boards);$("progress").innerHTML=boards.length?boards.map(b=>`<div class="progress-item"><div class="progress-head"><span>${esc(b.uid)}</span><span>${esc(b.state.toUpperCase())}</span></div><div class="progress-meta">${esc(b.phase)} · ${esc(b.percent)}% · ${duration(b.elapsed_seconds)} elapsed${b.bytes_per_second?` · ${(b.bytes_per_second/1024).toFixed(1)} KiB/s · ${Math.ceil(b.transferred_bytes/1024)} / ${Math.ceil(b.total_bytes/1024)} KiB`:''}${b.error?` · ${esc(b.error)}`:''}</div><progress value="${Math.max(0,Math.min(100,b.percent))}" max="100" aria-label="Board progress"></progress></div>`).join(''):"No operation started.";
 $("report").classList.toggle("hidden",!s.report_path);if(s.report_path)$("report").innerHTML=`<strong>Complete:</strong> ${boards.filter(b=>b.state==='passed').length} passed, ${boards.filter(b=>b.state==='partial').length} partial, ${boards.filter(b=>b.state==='failed').length} failed. <a href="/api/report" download>Download report</a><div class="detail">${esc(s.report_path)}</div>${s.general_error?`<div class="error">${esc(s.general_error)}</div>`:''}`;
 setMarkup("fleet",s.fleet.length?s.fleet.map(b=>`<label class="probe"><input type="checkbox" data-auto="${esc(b.uid)}" ${b.auto_update?'checked':''} ${s.running||busy?'disabled':''}><div><strong>Automatic updates · ${esc(b.label||b.uid)}</strong><div class="detail">${esc(b.ip)} · ${esc(b.last_version||'Prepared for first installation')}${b.last_error?` · ${esc(b.last_error)}`:''}</div></div></label>`).join(''):"No registered boards yet.");
 $("fleet").querySelectorAll('[data-auto]').forEach(el=>el.onchange=()=>action('/api/fleet/options',{uid:el.dataset.auto,auto_update:el.checked}));renderButtons();
}
function renderButtons(){if(!current)return;const s=current.state,locked=s.running||busy,ids=selectedIds(),net=mode()==='network-update';const valid=ids.length&&ids.every(id=>net?s.network_boards.some(b=>b.uid===id&&b.has_key&&!b.error):s.inspected[id]?.uid&&!s.inspected[id]?.error);['scan','release','included','network-scan','import-key','workers','resume-fleet'].forEach(id=>$(id).disabled=locked);document.querySelectorAll('input[name="mode"]').forEach(el=>el.disabled=locked);$("inspect").disabled=locked||!ids.length;$("start").disabled=locked||!valid||(mode()!=='erase-only'&&!s.release)||(['network-install','network-update'].includes(mode())&&!s.release?.network_supported);}
async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Installer unavailable');current=data;token=current.token;render();}catch(e){notice(e.message);}}
async function action(path,data={}){if(busy)return;busy=true;activeAction=path;render();try{await request(path,data);await refresh();}catch(e){notice(e.message);await refresh();}finally{busy=false;activeAction=null;render();}}
$("scan").onclick=()=>action('/api/scan');$("inspect").onclick=()=>action('/api/inspect',{serials:selectedIds()});$("release").onclick=()=>action('/api/release');$("included").onclick=()=>action('/api/included');$("network-scan").onclick=()=>action('/api/network/scan',{address:$("address").value.trim()});
$("import-key").onchange=async()=>{const file=$("import-key").files[0];if(!file)return;if(file.size!==64){notice('Choose a 64-byte board-access.g100-key file.');return;}const raw=new Uint8Array(await file.arrayBuffer());await action('/api/fleet/import',{record:btoa(String.fromCharCode(...raw))});await action('/api/network/scan');};
document.querySelectorAll('input[name="mode"]').forEach(el=>el.onchange=render);
$("start").onclick=()=>{
 const ids=selectedIds(),verb=mode()==='network-update'?'UPDATE':'ERASE';
 pendingReview={mode:mode(),serials:ids,max_parallel:Number($("workers").value),release_tag:current.state.release?.tag,confirmation:`${verb} ${ids.length}`};
 $("review-description").textContent=verb==='UPDATE'?"Install firmware over Ethernet and restart these boards. The previous confirmed image stays available until the new firmware passes its checks.":"Save verified backups, then erase these boards' internal Flash and external NOR, including settings and access records.";
 $("review-uids").textContent=ids.map(id=>verb==='UPDATE'?id:current.state.inspected[id].uid).join('\n');
 $("review-release").textContent=mode()==='erase-only'?'Erase only; no firmware will be installed.':`Firmware ${current.state.release.version} · ${current.state.release.tag}`;
 $("confirmation-phrase").textContent=pendingReview.confirmation;$("confirmation").value='';$("confirm-start").disabled=true;
 $("review-dialog").showModal();$("confirmation").focus();
};
$("confirmation").oninput=()=>{$("confirm-start").disabled=!pendingReview||$("confirmation").value!==pendingReview.confirmation;};
$("cancel-review").onclick=()=>$("review-dialog").close();
$("review-dialog").onclose=()=>{pendingReview=null;};
$("confirm-start").onclick=async()=>{if(!pendingReview||$("confirmation").value!==pendingReview.confirmation)return;const reviewed=pendingReview;$("review-dialog").close();await action('/api/start',reviewed);};
$("resume-fleet").onclick=()=>{if(confirm('Resume a release previously held after a failed board update? Review the report first.'))action('/api/fleet/resume');};
refresh();setInterval(refresh,2000);
